// Nexo 3.0 / ISO 20022 Protocol Standard & Adyen Terminal API Typings

export type NexoMessageClass = 'Service' | 'Device';

export type NexoMessageCategory = 
  | 'Payment'
  | 'CardAcquisition'
  | 'Reversal'
  | 'Diagnosis'
  | 'Display'
  | 'Input'
  | 'TransactionStatus'
  | 'EnableService'
  | 'Abort'
  | 'Event';

export type NexoMessageType = 'Request' | 'Response' | 'Notification';

export type NexoResult = 'Success' | 'Failure' | 'Partial';

export type NexoErrorCondition =
  | 'Aborted'
  | 'Busy'
  | 'Cancel'
  | 'DeviceOut'
  | 'InsertedCard'
  | 'InvalidCard'
  | 'LoggedOff'
  | 'MessageFormat'
  | 'NotAllowed'
  | 'NotFound'
  | 'PaymentRestriction'
  | 'Refusal'
  | 'UnavailableDevice'
  | 'UnavailableService'
  | 'Unspecified';

export interface NexoMessageHeader {
  ProtocolVersion: '3.0';
  MessageClass: NexoMessageClass;
  MessageCategory: NexoMessageCategory;
  MessageType: NexoMessageType;
  ServiceID: string; // 1-10 alphanumeric unique string generated by Sale POS
  SaleID: string; // Cash register identifier
  POIID: string; // Terminal identifier (e.g., S1F2-000154829102)
}

export interface NexoSaleTransactionID {
  TransactionID: string; // Client idempotency reference
  TimeStamp: string; // ISO 8601 or YYYY-MM-DDTHH:mm:ss.sssZ
}

export interface NexoAmountsReq {
  Currency: string;
  RequestedAmount: number;
  TipAmount?: number;
  CashBackAmount?: number;
}

export interface NexoSaleData {
  SaleTransactionID: NexoSaleTransactionID;
  SaleReferenceID?: string;
  SaleToAcquirerData?: string; // JSON string with metadata
  TokenRequestedType?: 'Customer' | 'Transaction';
  CustomerOrderReq?: string;
}

export interface NexoPaymentTransaction {
  AmountsReq: NexoAmountsReq;
  OriginalPOITransaction?: {
    SaleID: string;
    POIID: string;
    POITransactionID: {
      TransactionID: string;
      TimeStamp: string;
    };
    ReuseId?: string;
  };
  TransactionConditions?: {
    AllowedPaymentBrand?: string[];
    ForceOnlineFlag?: boolean;
    MerchantCategoryCode?: string;
  };
}

export interface NexoPaymentData {
  PaymentType: 'Normal' | 'Refund' | 'FirstInstallment' | 'Recurring';
  SplitPaymentFlag?: boolean;
}

export interface NexoPaymentRequest {
  SaleData: NexoSaleData;
  PaymentTransaction: NexoPaymentTransaction;
  PaymentData?: NexoPaymentData;
}

export interface NexoTransactionStatusRequest {
  MessageReference: {
    MessageCategory: 'Payment' | 'Reversal' | 'CardAcquisition';
    ServiceID: string;
    SaleID: string;
    POIID: string;
  };
  ReceiptRepReqFlag?: boolean;
  DocumentQualifier?: string[];
}

export interface NexoReversalRequest {
  OriginalPOITransaction: {
    SaleID: string;
    POIID: string;
    POITransactionID: {
      TransactionID: string;
      TimeStamp: string;
    };
    ReuseId?: string;
  };
  ReversalReason: 'MerchantCancel' | 'CustCancel' | 'Malfunction' | 'Unable2Complete';
  ReversedAmount?: number;
  SaleData?: {
    SaleTransactionID: NexoSaleTransactionID;
  };
}

export interface NexoDiagnosisRequest {
  HostStatus_Flag?: boolean;
}

export interface NexoCardAcquisitionRequest {
  SaleData: {
    SaleTransactionID: NexoSaleTransactionID;
  };
  CardAcquisitionTransaction?: {
    AllowedPaymentBrand?: string[];
    ForceCustomerSelectionFlag?: boolean;
  };
}

// Master Request Envelope
export interface SaleToPOIRequest {
  SaleToPOIRequest: {
    MessageHeader: NexoMessageHeader;
    PaymentRequest?: NexoPaymentRequest;
    TransactionStatusRequest?: NexoTransactionStatusRequest;
    ReversalRequest?: NexoReversalRequest;
    DiagnosisRequest?: NexoDiagnosisRequest;
    CardAcquisitionRequest?: NexoCardAcquisitionRequest;
  };
}

// Master Response Envelope
export interface NexoResponseStatus {
  Result: NexoResult;
  ErrorCondition?: NexoErrorCondition;
  AdditionalResponse?: string; // Form-urlencoded or JSON string from Adyen
}

export interface NexoPOITransactionID {
  TransactionID: string; // Adyen PSP Reference e.g. 883619284729104A
  TimeStamp: string;
}

export interface NexoPOIData {
  POIReconciliationID?: string;
  POITransactionID: NexoPOITransactionID;
}

export interface NexoCardData {
  PaymentBrand: string; // 'visa', 'mc', 'amex', 'rupay', 'alipay', etc.
  MaskedPan?: string; // '•••• •••• •••• 4892'
  CardBin?: string;
  IssuerCountry?: string;
  EntryMode?: ('ICC' | 'Tapped' | 'Contactless' | 'MagStripe' | 'Manual' | 'QRCode')[];
  PaymentToken?: {
    TokenValue: string;
    ExpiryDateTime?: string;
  };
}

export interface NexoPaymentResult {
  PaymentType: string;
  PaymentInstrumentData?: {
    PaymentInstrumentType: string;
    CardData?: NexoCardData;
  };
  AmountsResp?: {
    Currency: string;
    AuthorizedAmount: number;
    TipAmount?: number;
  };
  PaymentAcquirerData?: {
    AcquirerPOIID: string;
    AcquirerTransactionID?: {
      TransactionID: string;
      TimeStamp: string;
    };
    ApprovalCode: string;
    MerchantID: string;
  };
  OnlineFlag?: boolean;
}

export interface NexoPaymentResponse {
  Response: NexoResponseStatus;
  SaleData: NexoSaleData;
  POIData: NexoPOIData;
  PaymentResult?: NexoPaymentResult;
}

export interface NexoTransactionStatusResponse {
  Response: NexoResponseStatus;
  MessageReference?: {
    MessageCategory: string;
    ServiceID: string;
    SaleID: string;
    POIID: string;
  };
  RepeatedMessageResponse?: {
    MessageHeader: NexoMessageHeader;
    PaymentResponse?: NexoPaymentResponse;
    ReversalResponse?: NexoReversalResponse;
  };
}

export interface NexoReversalResponse {
  Response: NexoResponseStatus;
  POIData?: NexoPOIData;
  OriginalPOITransaction?: {
    POITransactionID: NexoPOITransactionID;
  };
  ReversedAmount?: number;
}

export interface NexoDiagnosisResponse {
  Response: NexoResponseStatus;
  POIStatus?: {
    GlobalStatus: 'OK' | 'Warning' | 'Unspecified';
    SecurityStatus: 'NoTamper' | 'Tampered';
    PEDOKFlag: boolean;
    CardReaderOKFlag: boolean;
    PrinterStatus: 'OK' | 'PaperLow' | 'NoPaper' | 'OutOfOrder';
    CommunicationOKFlag: boolean;
    BatteryLevelPercent?: number;
    FirmwareVersion?: string;
  };
  HostStatus?: {
    AcquirerID: string;
    IsReachable: boolean;
  }[];
}

export interface SaleToPOIResponse {
  SaleToPOIResponse: {
    MessageHeader: NexoMessageHeader;
    PaymentResponse?: NexoPaymentResponse;
    TransactionStatusResponse?: NexoTransactionStatusResponse;
    ReversalResponse?: NexoReversalResponse;
    DiagnosisResponse?: NexoDiagnosisResponse;
  };
}

// Adyen AdditionalResponse Parsed Structure
export interface AdyenParsedAdditionalResponse {
  pspReference: string;
  authCode?: string;
  merchantReference?: string;
  paymentMethod?: string;
  paymentMethodVariant?: string;
  cardSummary?: string;
  cardBin?: string;
  cardHolderName?: string;
  cardPaymentMethod?: string;
  issuerCountry?: string;
  offline?: boolean;
  offlineSignature?: string;
  refusalReason?: string;
  refusalReasonRaw?: string;
  shopperReference?: string;
  tenderReference?: string;
  store?: string;
  terminalId?: string;
}

// Adyen Webhook / Notification Schema (Async QR / Payment Events)
export interface AdyenNotificationRequestItem {
  additionalData: {
    'shopperReference'?: string;
    'authCode'?: string;
    'cardSummary'?: string;
    'paymentMethod'?: string;
    'expiryDate'?: string;
    'offline'?: string;
    [key: string]: string | undefined;
  };
  amount: {
    currency: string;
    value: number; // In minor units (cents / paise)
  };
  eventCode: 'AUTHORISATION' | 'CANCELLATION' | 'REFUND' | 'ORDER_OPENED' | 'PAYMENT_CAPTURED';
  eventDate: string;
  merchantAccountCode: string;
  merchantReference: string;
  paymentMethod: string;
  pspReference: string;
  reason?: string;
  success: 'true' | 'false';
  operations?: string[];
}

export interface AdyenWebhookNotification {
  live: 'true' | 'false';
  notificationItems: {
    NotificationRequestItem: AdyenNotificationRequestItem;
  }[];
}

// Adyen Terminal Hardware Profiles
export type AdyenTerminalModel = 
  | 'S1F2' 
  | 'AMS1' 
  | 'SATURN_1000F2' 
  | 'NYC1' 
  | 'TAP_TO_PAY';

export interface AdyenTerminalProfile {
  model: AdyenTerminalModel;
  name: string;
  subtitle: string;
  poiId: string;
  connectionType: 'CLOUD' | 'LOCAL_IP' | 'BLUETOOTH' | 'SOFTPOS';
  ipAddress?: string;
  hasPrinter: boolean;
  hasCameraScanner: boolean;
  batteryPercent: number;
  firmwareVersion: string;
  status: 'ONLINE' | 'OFFLINE' | 'BUSY';
}

// Store-and-Forward (SaF) Configuration retrieved from Adyen Customer Area
export interface AdyenSaFConfig {
  merchantAccount: string;
  poiId: string;
  store: string;
  safEnabled: boolean;
  maxSingleTransactionAmount: Record<string, number>; // Currency code -> Max amount
  maxCumulativeOfflineAmount: Record<string, number>; // Currency code -> Max cumulative
  maxOfflineTransactionCount: number;
  maxOfflineDurationHours: number;
  allowedPaymentBrands: string[];
  requireOfflinePin: boolean;
  supportedCurrencies: string[];
  lastSyncedTimestamp: string;
  configVersion: string;
}
